### ISSUE TITLE
Add a -version option

### ISSUE THREAD

**Issue by philrz** [brimdata/zync#14]
A while ago we made the `-version` option consistent across the Zed tools, which I found very useful since it made it easy to know the commit of the installed version when I was reporting problems. As of Zinger commit 16dc833 it looks like it doesn't yet exist.

```
$ zinger -version
flag provided but not defined: -version
at flag: "-version": flag provided but not defined: -version
```

**Comment by nwt** [comment]
#53 added a `zync version` command.
