### ISSUE TITLE
Install failed : 

### ISSUE THREAD

**Issue by kripskroll** [brimdata/zync#80]
I have an error with a module not find during install on my Linux Debian system

$ go get github.com/brimdata/zync/cmd/zync@main
build github.com/brimdata/zync/cmd/zync: cannot find module for path hash/maphash
$

Im blocked.
Just asked me anything you would need to better understand issue and I will provide.
Thanks in advance
--Krispkroll

**Comment by nwt** [comment]
@kripskroll: What does `go version` report?

**Comment by kripskroll** [comment]
go version go1.11.6 linux/amd64

**Comment by nwt** [comment]
@kripskroll: You'll need a newer Go version. Are you able to update to Go 1.16 or better?

**Comment by kripskroll** [comment]
@nwt : I install latest version.
```
$ go version
go version go1.18 linux/amd64
```

But now, when I try to install zync using : `$ go install github.com/brimdata/zync/cmd/zync@main`
Prompt is coming back without any message. Like if nothing has happen. And I feel like nothing happened.

I apologise. I never play with go and that is very new to me unfortunately.
Thanks for your patience.

**Comment by kripskroll** [comment]
@nwt : Perfect Thanks ! That works now :)
