### ISSUE TITLE
Add "-timeout" parameter in continuous "from-kafka" sync

### ISSUE THREAD

**Issue by philrz** [brimdata/zync#92]
For the continuous sync (#83) that's currently a work-in-progress in the `from-kafka-continuous` branch, a user has expressed the following requirement:

> I need the `-timeout` with `zync from-kafka` in the branch `from-kafka-continuous`
> This timeout will be in minute and it will stop zync process. It needs to force zync to reload a new YAML file.

**Comment by nwt** [comment]
#94 adds an `-exitafter` flag to `zync from-kafka`.
